<?php
/**
 * Win Equipments chat assistant endpoint.
 * Request:  POST JSON {"message": string, "history": [{"role": "user"|"assistant", "content": string}]}
 * Response: JSON {"success": bool, "reply": string}
 * Product facts come from chat_knowledge.php, generated by src/site/build.py from the catalogue data.
 */

header('Content-Type: application/json; charset=UTF-8');
header('X-Content-Type-Options: nosniff');

$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if ($origin && preg_match('#^https?://(localhost(:\d+)?|(www\.)?winequipments\.com)$#', $origin)) {
    header('Access-Control-Allow-Origin: ' . $origin);
    header('Vary: Origin');
}
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { respond(false, 'Method not allowed', 405); }

const WHATSAPP = 'https://wa.me/919597228969';
const PHONE = '+91 95972 28969';

/* ── input ─────────────────────────────────────────────────────────── */
$data = json_decode(file_get_contents('php://input') ?: '', true);
$message = trim(mb_substr((string)($data['message'] ?? ''), 0, 600));
if ($message === '') { respond(false, 'Empty message', 400); }
$history = [];
if (isset($data['history']) && is_array($data['history'])) {
    foreach (array_slice($data['history'], -6) as $m) {
        if (isset($m['role'], $m['content']) && in_array($m['role'], ['user', 'assistant'], true)) {
            $history[] = ['role' => $m['role'], 'content' => mb_substr((string)$m['content'], 0, 1200)];
        }
    }
}

$pageTitle = '';
if (isset($data['page']['title']) && is_string($data['page']['title'])) {
    $pageTitle = trim(preg_replace('/[^\p{L}\p{N} &,.\-\/()]/u', '', mb_substr($data['page']['title'], 0, 120)));
}

/* ── simple per-IP rate limit: 30 messages per 10 minutes ──────────── */
$ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
$bucket = sys_get_temp_dir() . '/win_chat_' . md5($ip);
$now = time();
$hits = array_filter(array_map('intval', @file($bucket, FILE_IGNORE_NEW_LINES) ?: []), fn($t) => $t > $now - 600);
if (count($hits) >= 30) {
    respond(true, "You've sent a lot of messages in a short time. For detailed help, please WhatsApp our engineers at " . WHATSAPP . " or call **" . PHONE . "**.");
}
$hits[] = $now;
@file_put_contents($bucket, implode("\n", $hits));

/* ── 1. quick deterministic answers ────────────────────────────────── */
$quick = quickAnswer($message);
if ($quick !== null) { respond(true, $quick); }

/* ── 2. language model, grounded in the catalogue data ─────────────── */
$knowledge = @include __DIR__ . '/chat_knowledge.php';
$apiKey = loadApiKey();
if ($apiKey && is_string($knowledge)) {
    $system = <<<EOT
You are the AI assistant on the Win Equipments website. Win Equipments is an industrial equipment manufacturer in Arasur, Coimbatore, India. Only if the visitor asks whether you are a person or an AI, say plainly that you are an AI assistant and that Win Equipments engineers confirm every selection and quotation. Otherwise do not mention it; the chat window already shows that you are an AI. Start directly with the answer.
Answer questions about Win Equipments products, help visitors pick a product or model, and guide them to request a quote.

Rules:
- Use ONLY the facts in the PRODUCT DATA below. If something is not there (prices, delivery times, warranty, stock, certifications other than those listed, brands of components, products not listed), say our engineers will confirm it and offer WhatsApp (https://wa.me/919597228969) or a call (+91 95972 28969).
- Never invent model numbers, capacities, figures or claims. Quote values exactly as written in the data.
- Win Equipments does not make air compressors, pumps, boilers, CNC or other machinery. Explain politely, then mention the related Win product (for example a dryer or chiller for that machine) if one fits.
- When recommending a model, give the model code, its rated capacity, and the product page link.
- For engineered-to-order products, list what information we need instead of quoting specs.
- Keep replies under 120 words. Use short paragraphs or bullets. You may use **bold** and plain links. No headings, no tables.
- Reply in the same language the visitor writes in (English or Tamil).
- End with a clear next step when the visitor seems ready: request a quote on the page, WhatsApp, or call.
- If the visitor says "this product" or similar, they mean the page they are viewing (below).

PRODUCT DATA:
{$knowledge}
EOT;
    if ($pageTitle !== '') { $system .= "\n\nThe visitor is currently viewing the page: {$pageTitle}"; }

    $contents = [];
    foreach ($history as $m) {
        $contents[] = ['role' => $m['role'] === 'assistant' ? 'model' : 'user', 'parts' => [['text' => $m['content']]]];
    }
    $contents[] = ['role' => 'user', 'parts' => [['text' => $message]]];
    $payload = json_encode([
        'systemInstruction' => ['parts' => [['text' => $system]]],
        'contents' => $contents,
        'generationConfig' => ['temperature' => 0.2, 'maxOutputTokens' => 500],
    ]);

    foreach (['gemini-3.5-flash-lite', 'gemini-3.5-flash'] as $model) {
        $ch = curl_init("https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key=" . urlencode($apiKey));
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $payload,
            CURLOPT_HTTPHEADER => ['Content-Type: application/json'],
            CURLOPT_TIMEOUT => 12,
            CURLOPT_CONNECTTIMEOUT => 4,
        ]);
        $raw = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($raw !== false && $code === 200) {
            $parsed = json_decode($raw, true);
            $text = trim($parsed['candidates'][0]['content']['parts'][0]['text'] ?? '');
            if ($text !== '') { respond(true, $text); }
        }
    }
}

/* ── 3. fallback when the model is unavailable ─────────────────────── */
respond(true, "I can't look that up right now. Our engineers can answer directly on WhatsApp: " . WHATSAPP . " or call **" . PHONE . "**.\n\n" .
    "Main ranges: **Refrigerated air dryers** WRD 10–2000 CFM · **Desiccant dryers** WHD 300–2000 CFM · **Process chillers** WCP 0.5–20 TR · **FRP cooling towers** WCT 10–300 TR · **Coil cooling towers** WCC 40–280 TR.");


/* ── helpers ───────────────────────────────────────────────────────── */
function respond(bool $ok, string $text, int $status = 200): void {
    http_response_code($status);
    echo json_encode($ok ? ['success' => true, 'reply' => $text] : ['success' => false, 'message' => $text]);
    exit;
}

function loadApiKey(): string {
    foreach ([dirname($_SERVER['DOCUMENT_ROOT'] ?? '') . '/secrets.php', '/home/winequipments/secrets.php', __DIR__ . '/secrets.php'] as $p) {
        if ($p && is_file($p)) { require_once $p; break; }
    }
    if (defined('GEMINI_API_KEY') && GEMINI_API_KEY) { return GEMINI_API_KEY; }
    return (string)(getenv('GEMINI_API_KEY') ?: '');
}

function quickAnswer(string $q): ?string {
    $l = mb_strtolower($q);

    // Compressor horsepower -> refrigerated dryer (rule of thumb ~4 CFM per HP; WRD ratings from the catalogue)
    if (preg_match('/(\d+(?:\.\d+)?)\s*(?:hp|horse\s*power)\b/u', $l, $m)) {
        $hp = (float)$m[1];
        $cfm = (int)round($hp * 4);
        $models = [20 => 'WRD 20 S', 40 => 'WRD 40 S', 50 => 'WRD 50 S', 60 => 'WRD 60 S', 80 => 'WRD 80 S', 100 => 'WRD 100 S',
            150 => 'WRD 150 S', 200 => 'WRD 200 S', 250 => 'WRD 250 S', 300 => 'WRD 300 T', 400 => 'WRD 400 T', 500 => 'WRD 500 T',
            600 => 'WRD 600 T', 750 => 'WRD 750 T', 1000 => 'WRD 1000 T', 1500 => 'WRD 1500 T', 2000 => 'WRD 2000 T'];
        $pick = null;
        foreach ($models as $cap => $name) { if ($cap >= $cfm) { $pick = "$name ($cap CFM)"; break; } }
        if ($pick === null) {
            return "A {$hp} HP compressor delivers roughly {$cfm} CFM, above our largest standard WRD dryer (2000 CFM). Our engineers can propose a solution: " . WHATSAPP;
        }
        return "A **{$hp} HP** compressor delivers roughly **{$cfm} CFM** (about 4 CFM per HP; use the free air delivery on your compressor nameplate for accuracy).\n\n" .
            "The matching refrigerated dryer at standard conditions is **{$pick}**, giving a +3 °C pressure dew point.\n\n" .
            "For hotter plants or other pressures, apply the correction factors on https://winequipments.com/products/refrigerated-air-dryers.html#sizing, or WhatsApp us: " . WHATSAPP;
    }

    // Chiller tonnage from flow and temperature difference: TR = LPM x dT / 50.4 (1 TR = 3024 kcal/h)
    if (preg_match('/(\d+(?:\.\d+)?)\s*(?:lpm|l\/min|litres? per min)/u', $l, $f) && preg_match('/(\d+(?:\.\d+)?)\s*(?:°\s*c|deg|degree|c\b)/u', $l, $t)) {
        $tr = round(((float)$f[1] * (float)$t[1]) / 50.4, 1);
        return "Heat load ≈ **{$tr} TR** (flow {$f[1]} LPM × ΔT {$t[1]} °C ÷ 50.4).\n\n" .
            "Our WCP process chillers cover 0.5 to 20 TR: https://winequipments.com/products/industrial-process-chillers.html. " .
            "Capacity also depends on the water outlet and ambient temperature, so share those and our engineers will confirm the model: " . WHATSAPP;
    }

    // Price and delivery: never quote numbers
    if (preg_match('/\b(price|pricing|cost|rate|quotation|quote|delivery|lead time)\b/u', $l)) {
        return "Prices and delivery depend on the model and your site conditions, so our engineers quote each enquiry.\n\n" .
            "Send your requirement with the **Request a quote** form on this page, WhatsApp " . WHATSAPP . ", call **" . PHONE . "** or email info@winequipments.com.";
    }

    return null;
}
