# Win Equipments: generated by src/site/build.py from src/site/htaccess.tpl and data/redirects.json. Do not edit public/.htaccess.
ErrorDocument 404 /404.html

<IfModule mod_rewrite.c>
    RewriteEngine On

    # HTTPS and non-www in one hop
    RewriteCond %{HTTPS} off [OR]
    RewriteCond %{HTTP_HOST} ^www\.winequipments\.com$ [NC]
    RewriteRule ^(.*)$ https://winequipments.com/$1 [L,R=301]

    # Old URLs (301)
{{REDIRECTS}}
</IfModule>

<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"
    Header always set Strict-Transport-Security "max-age=31536000"
    # HTML always revalidates; versioned CSS/JS and generated images are cached for a year
    <FilesMatch "\.(html|xml)$">
        Header set Cache-Control "no-cache"
    </FilesMatch>
    <FilesMatch "\.(css|js|woff2|avif|webp|png|jpg|jpeg|svg|mp4|webm)$">
        Header set Cache-Control "public, max-age=31536000, immutable"
    </FilesMatch>
    <FilesMatch "\.pdf$">
        Header set Cache-Control "public, max-age=604800"
    </FilesMatch>
</IfModule>

<IfModule mod_mime.c>
    # llms.txt and other .txt files carry degree signs and dashes; without this they are served with no charset
    AddDefaultCharset UTF-8
    AddType image/avif .avif
    AddType font/woff2 .woff2
    AddType video/mp4 .mp4
    AddType video/webm .webm
</IfModule>

<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json application/xml image/svg+xml
</IfModule>

# Server-side files that must never be downloaded
<FilesMatch "^(secrets|chat_knowledge)\.php$|^leads_.*\.csv$|\.(md|py|yml|log)$">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order deny,allow
        Deny from all
    </IfModule>
</FilesMatch>
